name: Publish Package

on:
  push:
    tags:
      - "v*"

jobs:
  publish-package:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          cache: false
          release: latest-including-prerelease

      - name: Build package
        uses: matlab-actions/run-build@v2
        with:
          tasks: package(Version="${{github.ref_name}}")

      - name: Draft release
        id: draft_release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: sample-*.mltbx
          # draft: true

      # - name: Publish release
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       github.rest.repos.updateRelease({
      #           owner: context.repo.owner,
      #           repo: context.repo.repo,
      #           release_id: ${{steps.draft_release.outputs.id}},
      #           draft: false,
      #       })
