name: Publish Package

on:
  push:
    tags:
      - "v*"

jobs:
  publish-package:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          cache: true
          release: latest-including-prerelease

      - name: Build package
        uses: matlab-actions/run-build@v2
        with:
          tasks: package(Version="${{github.ref_name}}")

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: sample-*.mltbx
          fail_on_unmatched_files: true
